### ISSUE TITLE
ArgumentError: wrong number of arguments (given 1, expected 2) in /monkey_patches/active_record.rb:55:in `render_bind'

### ISSUE THREAD

**Issue by guillehorno** [skaes/time_bandits#10]
Hi, 

After upgrading Rails to 5.0.3 I started seeing this error on the console, from the puma process. The full error is this one:
```
Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 1, expected 2)
```
Here's the call stack that I think its relevant:
```
[
"vendor/bundle/gems/time_bandits-0.10.4/lib/time_bandits/monkey_patches/active_record.rb:55:in `render_bind'",
"vendor/bundle/gems/time_bandits-0.10.4/lib/time_bandits/monkey_patches/active_record.rb:94:in `block in log_sql_statement'",
"vendor/bundle/gems/time_bandits-0.10.4/lib/time_bandits/monkey_patches/active_record.rb:94:in `map'",
"vendor/bundle/gems/time_bandits-0.10.4/lib/time_bandits/monkey_patches/active_record.rb:94:in `log_sql_statement'",
"vendor/bundle/gems/time_bandits-0.10.4/lib/time_bandits/monkey_patches/active_record.rb:81:in `sql'",
"vendor/bundle/gems/activesupport-5.0.3/lib/active_support/subscriber.rb:95:in `finish'",
"vendor/bundle/gems/activesupport-5.0.3/lib/active_support/log_subscriber.rb:83:in `finish'",
"vendor/bundle/gems/activesupport-5.0.3/lib/active_support/notifications/fanout.rb:102:in `finish'",
"vendor/bundle/gems/activesupport-5.0.3/lib/active_support/notifications/fanout.rb:46:in `block in finish'",
"vendor/bundle/gems/activesupport-5.0.3/lib/active_support/notifications/fanout.rb:46:in `each'",
"vendor/bundle/gems/activesupport-5.0.3/lib/active_support/notifications/fanout.rb:46:in `finish'",
"vendor/bundle/gems/activesupport-5.0.3/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'",
"vendor/bundle/gems/activesupport-5.0.3/lib/active_support/notifications/instrumenter.rb:27:in `instrument'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:587:in `execute_and_clear'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/query_cache.rb:93:in `block in select_all'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/query_cache.rb:108:in `cache_sql'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/query_cache.rb:93:in `select_all'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/querying.rb:39:in `find_by_sql'",
"vendor/bundle/gems/bullet-5.5.1/lib/bullet/active_record5.rb:25:in `find_by_sql'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/relation.rb:702:in `exec_queries'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/association_relation.rb:32:in `exec_queries'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/relation.rb:583:in `load'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/relation.rb:260:in `records'",
"vendor/bundle/gems/bullet-5.5.1/lib/bullet/active_record5.rb:52:in `records'",
"vendor/bundle/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `each'",
"app/models/position.rb:137:in `group_by'"]
```

Let me know if I can help with more context or something else. Thanks!

**Comment by skaes** [comment]
This has been fixed in https://github.com/skaes/time_bandits/commit/2e06f1f000904e13b968064c5b68896ff559d511. Please upgrade to the latest version.

**Comment by guillehorno** [comment]
Will do, thank you!!
